#include <chat/conversationclient.h>
#include <chat/conversationclientfactory.h>
#include <chat/conversationsnapshot.h>
#include <context/contextwindowservice.h>
#include <core/llmconfig.h>
#include <core/llmtypes.h>
#include <core/qtllmclient.h>
#include <events/illmeventsink.h>
#include <events/llmeventdispatcher.h>
#include <host/managedllamacppappbootstrap.h>
#include <host/modelcatalogservice.h>
#include <host/runtimefacade.h>
#include <host/runtimeprofile.h>
#include <host/runtimeprofilemapper.h>
#include <host/runtimerequesthandle.h>
#include <identity/compactid.h>
#include <logging/filelogsink.h>
#include <logging/ilogsink.h>
#include <logging/logtypes.h>
#include <logging/qtllmlogger.h>
#include <logging/signallogsink.h>
#include <network/httpexecutor.h>
#include <profile/clientprofile.h>
#include <profile/memorypolicy.h>
#include <providers/illmprovider.h>
#include <providers/llamacppprovider.h>
#include <providers/ollamaprovider.h>
#include <providers/openaicompatibleprovider.h>
#include <providers/openaiprovider.h>
#include <providers/providerfactory.h>
#include <providers/vllmprovider.h>
#include <qtllm_global.h>
#include <runtime/managedllamacppruntime.h>
#include <runtime/managedllamacppruntimeservice.h>
#include <storage/conversationrepository.h>
#include <streaming/streamchunkparser.h>
#include <structuredoutput/structuredoutputservice.h>
#include <structuredoutput/structuredoutputtypes.h>
#include <tools/builtintools.h>
#include <tools/llmtooladapter.h>
#include <tools/llmtooldefinition.h>
#include <tools/llmtoolregistry.h>
#include <tools/mcp/defaultmcpclient.h>
#include <tools/mcp/imcpclient.h>
#include <tools/mcp/mcp_types.h>
#include <tools/mcp/mcpservermanager.h>
#include <tools/mcp/mcpserverregistry.h>
#include <tools/mcp/mcpserverrepository.h>
#include <tools/mcp/mcptoolsyncservice.h>
#include <tools/protocol/itoolcallprotocoladapter.h>
#include <tools/protocol/providerprotocoladapters.h>
#include <tools/protocol/toolcallprotocolrouter.h>
#include <tools/runtime/builtinexecutors.h>
#include <tools/runtime/clienttoolpolicyrepository.h>
#include <tools/runtime/itoolexecutor.h>
#include <tools/runtime/toolcallorchestrator.h>
#include <tools/runtime/toolcatalogrepository.h>
#include <tools/runtime/toolexecutionlayer.h>
#include <tools/runtime/toolexecutorregistry.h>
#include <tools/runtime/toolruntime_types.h>
#include <tools/runtime/toolruntimehooks.h>
#include <tools/toolenabledchatentry.h>
#include <tools/toolselectionlayer.h>
#include <toolsinside/toolsinside_types.h>
#include <toolsinside/toolsinsideadminservice.h>
#include <toolsinside/toolsinsideartifactstore.h>
#include <toolsinside/toolsinsidei18n.h>
#include <toolsinside/toolsinsidequeryservice.h>
#include <toolsinside/toolsinsiderepository.h>
#include <toolsinside/toolsinsideruntime.h>
#include <toolsinside/toolsinsidetracerecorder.h>
#include <toolsstudio/toolcatalogservice.h>
#include <toolsstudio/toolimportexportservice.h>
#include <toolsstudio/toolmergeservice.h>
#include <toolsstudio/toolmetadataoverriderepository.h>
#include <toolsstudio/toolsstudio_types.h>
#include <toolsstudio/toolstudiosettings.h>
#include <toolsstudio/toolworkspacerepository.h>
#include <toolsstudio/toolworkspaceservice.h>

int main()
{
    return 0;
}
